### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by PixelsCommander** [PixelsCommander/HTML-GL#11]
In order to support retina displays we need to render textures in twice higher resolution than their screen dimensions

**Comment by PixelsCommander** [comment]
Also should support any devicePixelRatios different from 1

**Comment by corysimmons** [comment]
Ah, I was wondering why the demos were blurry for me.

**Comment by PixelsCommander** [comment]
Yep, sorry, it is a number one issue right now and quite hard to fix since html2canvas do not support retina. We work on this issue keeping two directions: fixing html2canvas and proposing native Rasterization API to w3c http://pixelscommander.com/en/javascript/state-of-html-content-rasterization-draw-html-to-canvas-image/ . Would be very pleased if you point to anyone in w3c community to contact with this proposal or just spread word about Rasterization API

**Comment by corysimmons** [comment]
Sorry @PixelsCommander I don't know anyone at the W3C but I'll look into the rasterization API and try to get the word out.

**Comment by nickdesaulniers** [comment]
![screen shot 2015-04-06 at 11 27 04 am](https://cloud.githubusercontent.com/assets/1823839/7009544/f3f825c2-dc4f-11e4-8c6f-03f90218de04.png)

**Comment by PixelsCommander** [comment]
@nickdesaulniers Yes, exactly, that is it.

**Comment by fandy** [comment]
From the demo it doesn't look like this has been fixed yet. Why was this abandoned?

**Comment by PixelsCommander** [comment]
It is fixed in master branch also there is a v2 branch which is a complete rewrite supporting 3D / VR and most efforts are spent on making it live
