### ISSUE TITLE
не ловит клики по верху картинки

### ISSUE THREAD

**Issue by makc** [PixelsCommander/HTML-GL#28]
на http://pixelscommander.com/polygon/htmlgl/demo/filters.html#.VQa1CrdZWvA

**Comment by makc** [comment]
как будто проверяешь по ректанглу

**Comment by PixelsCommander** [comment]
Как воспроизвести? У меня клик - alert, куда ни ткни.

**Comment by makc** [comment]
ну хз, на скриншотах курсора невидно. ща придумаю что нибудь

**Comment by makc** [comment]
[тут](https://www.youtube.com/watch?v=OFZXAcoR6Uk) погляди через полчасика

**Comment by makc** [comment]
мне кажется дело вот в чем:

![-_-](http://i.imgur.com/xNBiZk6.png)

добавь pointer-events: none туда

**Comment by PixelsCommander** [comment]
Думаешь? А попробуй в том месте где ты кликаешь и не получаешь ответа
кликнуть DOM инспектором? Мне кажется там просто дисплейсмент чуть выше
поднимает картинку а на деле ее img лежит ниже.

2015-03-17 13:54 GMT+01:00 makc <notifications@github.com>:
