### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by Suor** [PixelsCommander/HTML-GL#34]
Tried on Ubuntu 14.10, Chrome 41 and Firefox 36. Also on Mac OS X 10.9.5, Chrome 41.

**Comment by PixelsCommander** [comment]
Could you provide console log for that?

**Comment by PixelsCommander** [comment]
Not needed, sorry, got it as well

**Comment by PixelsCommander** [comment]
Not needed, got it as well

**Comment by PixelsCommander** [comment]
Fixed
