### ISSUE TITLE
SVG support 

### ISSUE THREAD

**Issue by ojosdegris** [PixelsCommander/HTML-GL#35]
Does it support svg as well? Is there any demo with svg?

**Comment by PixelsCommander** [comment]
Nice point. Will create one. Should be not that hard.

**Comment by ojosdegris** [comment]
Thanks!

**Comment by PixelsCommander** [comment]
Just tried <html-gl><img src='some.svg'></html-gl> and it worked like a charm. So, go ahead with no worries.

**Comment by ojosdegris** [comment]
Cool, thanks!

I'll try to use it with our svg-based product.

**Comment by PixelsCommander** [comment]
:+1: Just let me know if there are difficulties, will figure them out.
