### ISSUE TITLE
Internet Explorer Compatibility

### ISSUE THREAD

**Issue by m1m1k** [PixelsCommander/HTML-GL#36]
Being a long-time web dev myself, I just wanted to try other browsers to see what happened.
I'm surprised and happy to say that *some* of the functionality works (background displacement), but the rest of the filters in your demo only applied to the background elements, so it looks like the original html elements are not hidden? or something like that.

For example, turning on Twist, Displacement, and RGB gives the following:

![image](https://cloud.githubusercontent.com/assets/1581534/6970160/90397682-d928-11e4-923d-e21e145a8064.png)

I'm using Internet Explorer 11.0.9600.17691 (latest) on Windows 7 x64.

![image](https://cloud.githubusercontent.com/assets/1581534/6970083/1962d012-d928-11e4-9bdc-01ff3ceb8125.png)

**Comment by PixelsCommander** [comment]
Thanks for reporting. Will fix

**Comment by PixelsCommander** [comment]
Fixed
