### ISSUE TITLE
Framebuffer does not clean correctly in firefox, windows, video board Intel HD 4000

### ISSUE THREAD

**Issue by brunobg** [PixelsCommander/HTML-GL#44]
This happens when dragging http://pixelscommander.com/polygon/htmlgl/demo/advanced-content-webgl.html in Firefox 36.0.4 Windows. It seems that the background is not cleaned (or rendered correctly) in the framebuffer when a DOM node is moved.

![webgl](https://cloud.githubusercontent.com/assets/798800/6984394/c9d18f20-d9fe-11e4-8f53-32504cd8ed0e.png)

Other than that, great project.

**Comment by PixelsCommander** [comment]
What is the model of your video board? Is it Intel HD 4000 or GeForce 740?

**Comment by brunobg** [comment]
It's a dual Intel HD 4000/Nvidia GT 635M. Using Intel generates these artifacts. Forcing NVidia crashed the browser during the demo page load.

**Comment by brunobg** [comment]
Works fine in the same PC, Chrome 41, using Intel.

**Comment by PixelsCommander** [comment]
Try this one http://pixelscommander.com/polygon/htmlglpixiv3/demo/advanced-content-webgl.html is problem still there ?

**Comment by brunobg** [comment]
No artifacts when I drag, so problem fixed.
 
Two other points worth relating: 

- The click does not work correctly (the clicks are detected always in the same position, as if it was never dragged at all). 
-There is no background animation, I don't know if there should be one.

**Comment by PixelsCommander** [comment]
That was just a guess how to fix that, not actual fix. It will take some time to implement that entirely.

**Comment by PixelsCommander** [comment]
Duplicate. Will be fixed as a part of #52
