### ISSUE TITLE
Integration with frameworks?

### ISSUE THREAD

**Issue by dnbard** [PixelsCommander/HTML-GL#56]
Hello. I'm using React and looks like HTML-GL aren't working fine with it.

My application with React only:

![2015-05-31_2127](https://cloud.githubusercontent.com/assets/4028472/7903145/fa34d6e4-07db-11e5-9dc6-716839c9c3b1.png)

And with React + HTML-GL:

![2015-05-31_2129](https://cloud.githubusercontent.com/assets/4028472/7903155/1dbc39e0-07dc-11e5-9a0d-578780468c30.png)

* styles broken
* missing the scrollbar
* onClick handlers aren't working correctly

Does HTML-GL integrated with frameworks such as React?

**Comment by PixelsCommander** [comment]
Hi

This is styling issue during rasterization and it is not related to React or frameworks compatibility. I d like to figure it out but need a code for that. Static HTML is enough.

**Comment by dnbard** [comment]
@PixelsCommander sources are here => https://github.com/dnbard/solar (HTML-GL isn't included). You will need to `npm install` the dependencies and then run `gulp` to build sources and run the dev server.

**Comment by PixelsCommander** [comment]
Why do you need HTML GL there? There is nothing to animate at 60 FPS.

Try to switch particles to transform: translate3d(x,y,0) instead of
left/top. Will make it much better. HTML GL will need every particle to be
<html-gl> tag because GPU operates rasterized textures.

2015-06-01 9:49 GMT+02:00 Alex Bardanov <notifications@github.com>:

**Comment by dnbard** [comment]
Thanks for `translate3d` suggestion!

```HTML GL will need every particle to be <html-gl> tag...```

There is no such details available in HTML-GL docs. Just `include your app into the <html-gl></html-gl> and GL magic will do everything else for you`(which is a little confusing in case of this app).

**Comment by PixelsCommander** [comment]
I do not know where this text is from. HTML GL is extremely easy to use and start with comparing to WebGL but you still need to take into account how GPU works (sending texture from CPU to GPU takes some time).

Added some hints to README under:
- Fast way to animate
- Animating HTML-GL tag children
