### ISSUE TITLE
Contents of inline frames (iframe) are not rendered

### ISSUE THREAD

**Issue by 39bit** [PixelsCommander/HTML-GL#62]
While the border of the respective iframe does render, the actual contents are invisible. Despite this, all the links inside the page are still actually clickable, as if it was there, but the page itself is never rendered.

Tested for both `<html-gl>` and jQuery plugin, and on Firefox 40.0.3 and Chrome 44.0.

**Comment by PixelsCommander** [comment]
This is not supported by rasterization library we use. Spread the word on rasterization API if interested in solving this http://pixelscommander.com/en/javascript/state-of-html-content-rasterization-draw-html-to-canvas-image/
