### ISSUE TITLE
DOM Manipulation Performance

### ISSUE THREAD

**Issue by goersen** [PixelsCommander/HTML-GL#65]
Hi,
I'm currently reviewing some Web-GL Frameworks regarding their performance, featureset etc.
HTML-GL looks very much like an awesome job done, great work!

But I'm having an Issue regarding some basic functionality on DOM-Manipulation. Consider this super simple page:

```html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script src='vendor/htmlgl/htmlgl.min.js'></script>
    <script src='vendor/htmlgl/htmlgl-effects.min.js'></script>
</head>
<body>
	<div><button onclick="window._start('_testGL');">Test HTML-GL</button></div>
	<div><button onclick="window._start('_testPlain');">Test Plain HTML</button></div>
	<html-gl id="test-gl"></html-gl>
	<div id="test-plain"></div>
</body>
<script type="text/javascript">
	window._testGL = document.getElementById('test-gl');
	window._testPlain = document.getElementById('test-plain');
	window._str = '';
	for (var i = 0; i < 100; i++) {
		window._str += '<div class="big"><div class="title"><div>hello world</div></div><div class="inner">the content</div></div>';
	};
	console.log('string prepared');

	window._running = false;
	window._start = function(element) {
		if(window._running) {
			return;
		}
		
		window._running = true;
		window[element].innerHTML = window._str;
	}
</script>
</html>
```

Try it and you will see, that HTML-GL takes some time, while plain HTML renders everything instantly. Increasing the loop-counter will eventually break the canvas.

This is just a List of 100 unstyled items simulating a title and content, so I assume I'm doing something wrong. Could you point me in the right direction, or are Item-Lists (i.e. a few more elements)  something HTML-GL is not made for?

Thanks and keep up the awesome work!

**Comment by PixelsCommander** [comment]
Hello

Every time you update content of html-gl element you do rasterization
operation and uploading rasterized content to GPU. You may try making every
list item a new html-gl. This will not update the rest.

2015-10-09 22:45 GMT+02:00 goersen <notifications@github.com>:
