### ISSUE TITLE
Problem when include jquery

### ISSUE THREAD

**Issue by vinhtq** [PixelsCommander/HTML-GL#69]
I included jquery in project and try to run but always get this error:
```
ReferenceError: propellerObj is not defined
```

So i tried to run you example: basic-webgl-jquery.html

I got the same error. Could you please tracking this problem?

**Comment by jackrugile** [comment]
+1

**Comment by PixelsCommander** [comment]
Hi guys,

Was sure it is gone long time ago. Will have a look.

2016-07-13 5:23 GMT+02:00 Jack Rugile <notifications@github.com>:

**Comment by zbryikt** [comment]
+1 
![screen shot 2016-08-19 at 1 27 24 am](https://cloud.githubusercontent.com/assets/2672307/17783791/2738eda4-65ac-11e6-8f9c-5dae4196dd5b.png)

**Comment by PixelsCommander** [comment]
Resolved
