### ISSUE TITLE
Technical limitations on retina support?

### ISSUE THREAD

**Issue by corysimmons** [PixelsCommander/HTML-GL#71]
It'd just be rendering a 2x texture as well right?

**Comment by corysimmons** [comment]
Nevermind, I see you added retina support. Please update demos. =)

**Comment by PixelsCommander** [comment]
@corysimmons Yeah, it was tricky a bit, had to hack html2canvas. Found it a big problem to establish communication with its author and making pull request so had to include custom html2canvas version into build.
