### ISSUE TITLE
[Question] Status of HTML-GL v2

### ISSUE THREAD

**Issue by KrzysztofWrobel** [PixelsCommander/HTML-GL#85]
Hey,

I was wondering, what is the current status of V2? Is it stable enough to use it in production?

I've found a presentation about it, when I was looking for an efficient html rendering on textures inside WebVR. :)

**Comment by PixelsCommander** [comment]
Yes, it is good. Not released just because there is still no 2d rendering as in v1 but is ready for using in WebVR
Hint - use zero transforms on elements you are going to animate. Check demos.

**Comment by KrzysztofWrobel** [comment]
Thanks man, I will do that.

**Comment by irisjay** [comment]
whats the difference with v1? whats this slide you mentioned? immensely curious! thanks
