### ISSUE TITLE
HTML-GL can be used to render to video? 

### ISSUE THREAD

**Issue by drschwabe** [PixelsCommander/HTML-GL#87]
Is there a way to render the output of an html-gl element to a video format like MP4 ? 

I'm looking for a way to render an HTML page (ie containing a slideshow and JS/CSS driven animations)  into an HD MP4 and my research brought me here - any insights or detail on how this might be acommodated via HTML-GL are appreciated.

**Comment by PixelsCommander** [comment]
so essentially you need to convert it to a series of screenshots and then convert to video, I would say this is not possible in a runtime but for screenshots would recommend to read my article on it http://pixelscommander.com/javascript/state-of-html-content-rasterization-draw-html-to-canvas-image/ and then use something like http://libwebpjs.appspot.com/v0.1.3/ to convert screenshots to video. Also consider new player on the block when it comes to content rasterization - https://github.com/tsayen/dom-to-image

I am open for consulting if you have any difficulties.

**Comment by drschwabe** [comment]
Great !  Thanks for your detailed insight/suggestion and article on the topic - as well as the headusp about dom-to-image

**Comment by RationalCoding** [comment]
Call `canvas.captureStream()` on the canvas being used to render (it's a direct child of the body) and you'll get a MediaStream with your html-gl rendered content.

**Comment by drschwabe** [comment]
Nice thinking!  Thanks @RationalCoding 
Not too experienced in canvas yet but hopeful that the MediaStream would be able to capture every frame ie- an animation @ 30 FPS
