### ISSUE TITLE
Will it boost css rendering generally or only animations?

### ISSUE THREAD

**Issue by Kuurusch** [PixelsCommander/HTML-GL#92]
Hey, I'm working on a project were I have to display 10'000 of items in a timeline (using vis.js; http://visjs.org/) and my problem is, that it took very long to render it. Would the use of HTML-GL boost such a timeline-rendering or is it more thougth for css effects and animations?

Thanks for your help!

**Comment by PixelsCommander** [comment]
Hi

Sorry, ve been on vacation. This boosts animations only.
